{% set name = "ondamonitor" %}
{% set version = "23.8.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/omdevteam/om/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2a2c9d51f2fa6b29d228a9605cef280f0bda2b5adc3b282f881d6b0399754da4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [not linux64]


requirements:
  build:
    - {{ compiler("cxx") }}
    - make
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - numpy
    - setuptools
    - pip
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - numpy
    - click
    - fabio
    - hdf5plugin
    - h5py
    - msgpack-numpy
    - msgpack-python
    - mpi4py
    - mypy_extensions
    - openssh
    - pillow
    - pyqt
    - pyqtgraph
    - pyyaml
    - pyzmq
    - rich
    - ruamel_yaml
    - scipy
    - typing

test:
  imports:
    - om
    - om.algorithms
    - om.data_retrieval_layer
    - om.graphical_interfaces
    - om.lib
    - om.parallelization_layer
    - om.processing_layer
    - om.protocols
  commands:
    - om_monitor.py --help

about:
  home: https://www.ondamonitor.com
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Real-time monitoring of x-ray imaging experiments'
  description: |
    OM (OnDA Monitor) is a framework for the development of programs
    that can monitor x-ray imaging experiments in real-time. It is
    also a set of ready-to-use monitoring programs. It is the
    spiritual successor of the OnDA Project and it is maintained
    mostly by the same team of developers. OM offers a set of stable
    and efficient real-time monitoring programs for the most common
    types of x-ray imaging experiments. These can be used immediately
    without modifications or can be easily adapted to meet the users’
    requirements. In addition, the project provides a set of modules
    that can be used to easily develop other monitoring programs,
    tailored to the characteristics of specific experiments.
  doc_url: https://www.ondamonitor.com
  dev_url: https://github.com/omdevteam/om

extra:
  recipe-maintainers:
    - valmar
